public class ListExample1 {
    public static void listEaxmple(){
        Set <Integer> num = new Set <Integer>();
        num.add(1);
        num.add(2);
        num.add(3);
        num.add(4);
        System.debug('The List of Numbers ' +num);
        
                List <Integer> num1 = new List <Integer>();
        num1.add(30);
        num1.add(20);
        num1.add(60);
num.addAll(num1);
             System.debug('The List of Numbers ' +num);
   
    }
}